In [3]:
import numpy as np
a = np.array([1,2,3])
b= np.array([4,5,6])

In [4]:
c = a+b 

In [5]:
c

array([5, 7, 9])

# aggregate operation 

In [6]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.sum(a,axis = 1)

array([ 6, 15])

# Array indexing and slicing

In [8]:
a[1,1]

5

# Array manipulation 

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,10,91])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18,
       19, 10, 91])

In [19]:
t=a.reshape(4,5)


In [20]:
t

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 10, 91]])

In [31]:
arr_1 =np.array([23,34,45,67,89])
arr_1

array([23, 34, 45, 67, 89])

In [24]:
t2 = np.append(t,[arr_1],axis = 0)
t2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 10, 91],
       [23, 34, 45, 67, 81]])

In [47]:
j = arr_1.reshape(5,-1)

In [48]:
j

array([[23],
       [34],
       [45],
       [67],
       [89]])

In [50]:
import numpy as np
 
numbers = np.arange(1,21)
numbers = numbers.reshape(4,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
extras = np.array([21,22,23,24,25])
j = extras.reshape(5,-1)
j

array([[21],
       [22],
       [23],
       [24],
       [25]])

In [52]:
numbers = np.append(numbers,extras.reshape(5,-1),axis=1)
print ( numbers )

ValueError: all the input array dimensions except for the concatenation axis must match exactly