In [1]:
# without numpy
import time 
 
sum = 0
 
start_time = time.time()
 
for num in range(10000000) :
    sum = sum + num
     
print ( "sum = ", sum)
 
end_time = time.time()
 
python_time = end_time - start_time
 
print ( "time taken = ", python_time)


sum =  49999995000000
time taken =  1.5059070587158203


In [2]:
# with numpy
import numpy as np
import time
 
sum = 0
 
start_time = time.time()
 
numbers = np.arange(10000000)
 
sum = np.sum(numbers, dtype = np.uint64)
print ( "sum = ", sum)
 
end_time = time.time()
 
numpy_time = end_time - start_time
factor = python_time / numpy_time
 
print ( "time taken = ", (end_time - start_time))
 
print ( "numpy is ", factor , " times faster than standard python")

sum =  49999995000000
time taken =  0.0631554126739502
numpy is  23.84446550116462  times faster than standard python


# Numpy Arrays 

In [3]:
import numpy as np
 
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
b = np.array( [[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10],
               [11,12,13,14,15,16,17,18,19,20]])
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [6]:
#range
n = np.arange(10)

In [7]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
a.shape

(12,)

In [10]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [14]:
numbers_1 = [1,2,3]
numbers_2 = [4,5,6]
numbers_3 = [7,8,9]
a = np.array([numbers_1 + numbers_2 + numbers_3])

In [15]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
numbers = np.arange(1,13) 
numbers.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
numbers.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])