In [1]:
import numpy as np
 
numbers = np.arange(1,21)
numbers = numbers.reshape(4,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [2]:
extras = np.array([21,22,23,24,25])
print ( extras)


[21 22 23 24 25]


In [3]:
numbers_new = np.insert(numbers,2,extras,axis=0)
numbers_new


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
# vertical 

numbers = np.arange(1,21)
numbers = numbers.reshape(4,5)
numbers


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
extras = np.array([21,22,23,24])
print ( extras)


[21 22 23 24]


In [6]:
numbers_new = np.insert(numbers,3,extras,axis=1)
print ( numbers_new)


[[ 1  2  3 21  4  5]
 [ 6  7  8 22  9 10]
 [11 12 13 23 14 15]
 [16 17 18 24 19 20]]


# Deletion

In [7]:
numbers = np.arange(1,21)
numbers = numbers.reshape(4,5)
numbers


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
numbers_new = np.delete(numbers,2,axis=1)
print ( numbers_new )


[[ 1  2  4  5]
 [ 6  7  9 10]
 [11 12 14 15]
 [16 17 19 20]]
